
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("                A           L              P P P P P      H       H            A            L             I I I I I      F F F F F      E E E E E")
print("               A A          L              P       P      H       H           A A           L                 I          F              E")
print("              A   A         L              P P P P P      H H H H H          A   A          L                 I          F F F F F      E E E E E")
print("             A  A  A        L              P              H       H         A  A  A         L                 I          F              E")
print("            A       A       L              P              H       H        A       A        L                 I          F              E")
print("           A         A      L L L L L      P              H       H       A         A       L L L L L     I I I I I      F              E E E E E")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")